---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by crist yang.
--- DateTime: 2025/7/17 15:10
---
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0
